services:
    anix.bur.listener:
        class: anix\bur\event\listener
        arguments:
            - '@request'
            - '@user'
            - '@dbal.conn'
            - '@language'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
